---
apiVersion: v1
kind: Pod
metadata:
  name: kubapp
  labels:
    app: kubapp

spec:
  containers:
    - name: kub-app-con
      image: tomcat:latest
      ports:
        - name: http
          containerPort: 8080


